### PR TITLE
Remove plyr

### PR DESCRIPTION
**Pull request by krlmlr**
As discussed.

### CODE REVIEW

**Comment by krlmlr** [comment]
One instance of `plyr::dlply()` remains, in `as.mcmcr.mb_analysis_coef()`, but it's not covered by the tests yet.

**Comment by joethorley** [comment]
Waiting on nmbr development. Likely not needed.

**Review by joethorley — COMMENTED** [review]
Likely not worth following through as development moving to nmbr

**Review by joethorley — APPROVED** [review]
good to be getting off plyr

**Pull request merged**
