### PR TITLE
feat: Implement `"pmb_code"` class to support a strict subset of the nimble language

### PR DESCRIPTION
**Pull request by krlmlr**
New methods from the (now archived) pmbr package are inlined here.

### CODE REVIEW

**Review by joethorley — APPROVED** [review]
It looks great!

**Review by joethorley — APPROVED** [review]
This is great

**Comment by krlmlr** [comment]
Can you please try a few of your or your team's recent analyses with this version? These should work out of the box, except that you now need `model(code = "...")` instead of `model("...")` to avoid deprecation warnings. You can `pak::pak("poissonconsulting/poispkgs@pmbr6", ask = FALSE)` to get it, or just install this branch. (The branches for the jmbr and tmbr packages are needed only to fix tests.)

**Comment by krlmlr** [comment]
- Should it be `engine = "jmbr"` or `"rjags"`? I suspect the latter would be more natural.
- One thing we're not doing yet: check for the presence of `^ -2` or `1 / ` in the `sd` term. I can add that.

**Comment by joethorley** [comment]
I'm thinking it should be `engine = "jags"`

**Comment by joethorley** [comment]
I just ran on a jags and stan analysis and it worked perfectly

**Comment by joethorley** [comment]
also on TMB

**Pull request merged**
